version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: login_db
      MYSQL_USER: utenteweb
      MYSQL_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/ssl/certs
      - .:/var/www/html
    depends_on:
      - web

volumes:
  db_data:
